# Generated by Django 4.2.1 on 2023-05-27 12:09

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter a producer name', max_length=50)),
                ('phone', models.CharField(help_text='Enter a producer phone', max_length=50)),
                ('address', models.CharField(help_text='Enter a producer address', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter a product type (e.g. Oil, Tire etc.)', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter a provider name', max_length=50)),
                ('phone', models.CharField(help_text='Enter a provider phone', max_length=50)),
                ('address', models.CharField(help_text='Enter a provider address', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('article', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this product', primary_key=True, serialize=False)),
                ('price', models.IntegerField()),
                ('producer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='test_app.producer')),
                ('product_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_app.producttype')),
                ('providers', models.ManyToManyField(help_text='Select a provider for this product', to='test_app.provider')),
            ],
        ),
    ]
