# Generated by Django 4.2.1 on 2023-05-28 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0002_person_alter_producer_address_alter_producer_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bye',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('article', models.UUIDField()),
                ('count', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Person',
        ),
    ]
