# Generated by Django 4.2.1 on 2023-05-29 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0003_bye_delete_person'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bye',
            name='article',
        ),
        migrations.AddField(
            model_name='bye',
            name='product_name',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
    ]
