# Generated by Django 4.2.1 on 2023-07-15 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0004_remove_bye_article_bye_product_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bye',
            name='product_name',
            field=models.CharField(help_text='Name of product', max_length=64),
        ),
        migrations.AlterField(
            model_name='producer',
            name='address',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='producer',
            name='name',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='producer',
            name='phone',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='producttype',
            name='name',
            field=models.CharField(help_text='Enter a product type (e.g. Oil, Tire etc.)', max_length=64),
        ),
        migrations.AlterField(
            model_name='provider',
            name='address',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='provider',
            name='name',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='provider',
            name='phone',
            field=models.CharField(max_length=64),
        ),
    ]
