# Generated by Django 4.2.1 on 2023-07-15 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0005_alter_bye_product_name_alter_producer_address_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Bye',
            new_name='Buy',
        ),
    ]
