# Generated by Django 4.2.1 on 2023-08-09 20:18

from django.conf import settings
from django.db import migrations
import shop_app.m2m_validation
import shop_app.validators


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop_app', '0026_rename_providers1_product_providers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='providers',
            field=shop_app.m2m_validation.ValidatedManyToManyField(blank=True, help_text='Select a provider for this product', to=settings.AUTH_USER_MODEL, validators=[shop_app.validators.validate_provider]),
        ),
    ]
