# Generated by Django 4.2.1 on 2023-08-27 17:20

import apps.core.media_tools.storages
import apps.core.model_tools.named_image_field
import apps.core.model_tools.svg_field
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0037_alter_provider_options_category_image_category_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=apps.core.model_tools.named_image_field.NamedImageField(default='categories_images/image_default.png', storage=apps.core.media_tools.storages.OverwriteCodedStorage(), upload_to='categories_images'),
        ),
        migrations.AlterField(
            model_name='category',
            name='logo',
            field=apps.core.model_tools.svg_field.SvgField(default='categories_logo/logo_default.svg', storage=apps.core.media_tools.storages.OverwriteCodedStorage(), upload_to='categories_logo', validators=[apps.core.model_tools.svg_field.validate_svg, apps.core.model_tools.svg_field.validate_svg]),
        ),
    ]
