# Generated by Django 4.2.1 on 2023-08-28 19:43

import apps.core.media_tools.storages
import apps.core.model_tools.svg_field
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0038_alter_category_image_alter_category_logo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='provider',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.AddField(
            model_name='category',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='category',
            name='logo',
            field=apps.core.model_tools.svg_field.SvgField(default='categories_logo/logo_default.svg', storage=apps.core.media_tools.storages.OverwriteCodedStorage(), upload_to='categories_logo', validators=[apps.core.model_tools.svg_field.validate_svg, apps.core.model_tools.svg_field.validate_svg]),
        ),
        migrations.AlterField(
            model_name='product',
            name='article',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique ID for this product', primary_key=True, serialize=False),
        ),
    ]
