# Generated by Django 4.2.1 on 2023-09-27 20:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0063_alter_carouselitem_content'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carouselitem',
            options={'ordering': ('id',)},
        ),
        migrations.AddField(
            model_name='review',
            name='date',
            field=models.DateField(default=datetime.date.today, editable=False),
        ),
        migrations.AlterField(
            model_name='carouselitem',
            name='content',
            field=models.TextField(default='<div style="text-align: center;color: #f2f2f2;font-size: 15px;">\n    <h1 style=\'margin-bottom:100px; font: 62.5% "Roboto","Arial","Helvetica",sans-serif; font-size: 5em; font-weight: 700;\'>\n        Create\n    </h1>\n    <h3 style=\'font: 62.5% "Roboto","Arial","Helvetica",sans-serif; font-size: 1.9em;\'>\n        Our workers are the best\n    </h3>\n</div>\n'),
        ),
    ]
