# Generated by Django 4.2.1 on 2023-09-28 21:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0065_alter_review_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='date',
            field=models.DateField(auto_now_add=True, editable=False),
        ),
        migrations.AlterField(
            model_name='faq',
            name='date',
            field=models.DateField(auto_now_add=True, editable=False),
        ),
    ]
