# Generated by Django 4.2.1 on 2023-09-29 19:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0065_alter_review_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='date',
            field=models.DateField(auto_now_add=True, default=datetime.date(2023, 9, 29)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='faq',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
