# Generated by Django 4.2.1 on 2023-11-01 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0066_news_date_alter_faq_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='birthday',
            field=models.DateField(editable=False),
        ),
    ]
