# Generated by Django 4.2.1 on 2023-08-10 19:31

from django.conf import settings
from django.db import migrations
import apps.shop_app.m2m_validation
import apps.shop_app.validators


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop_app', '0027_alter_product_providers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='providers',
            field=apps.shop_app.m2m_validation.ChoicesValidatedManyToManyField(blank=True, help_text='Select a provider for this product', related_name='products', to=settings.AUTH_USER_MODEL, validators=[apps.shop_app.validators.validate_provider]),
        ),
    ]
